spring.application.name=my-basic-project

# Use wildcard "*" to expose all actuator endpoints
management.endpoints.web.exposure.include=*
# Can also expose individual actuator endpoints with a comma-delimited list.
#management.endpoints.web.exposure.include=health,info
management.info.env.enabled=true

# Exclude individual actuator endpoints
#management.endpoints.web.exposure.exclude=health,info

info.app.name=My Basic Project
info.app.description=A basic project to test Spring Boot
info.app.version=1.0

coach.name=Mickey Mouse
team.name=The Mouse Club

server.port=7070
server.servlet.context-path=/mybasicproject